import Head from 'next/head';
import Table from './components/Table';
import styles from '../styles/Home.module.css';
import {ReactElement, JSXElementConstructor, useState} from 'react';

export default function Home() {
 const [type, setType] = useState('radio');
 const [selectedRowKeys, setSelectedRowKeys] = useState(['1']);

  const selectedRowType = [ 'radio', 'checkbox'];
  const columns = [
        {
            title: 'Operator',
            key: 'operator',
            dataIndex: 'operator',
            render: (e:  ReactElement<any, string | JSXElementConstructor<any>> ) => <span >{e}</span>,
       },
       {
           title: 'Headset Display',
           key: 'display',
           dataIndex: 'display',
           render: (e:  ReactElement<any, string | JSXElementConstructor<any>> ) => <span >{e}</span>,
       },
       {
         title: '3G Availability',
         key: 'availability',
         dataIndex: 'availability',
         render: (e:  ReactElement<any, string | JSXElementConstructor<any>> ) => <span >{e}</span>,
      },
  ];
  const data = [
      {
          id: 1,
          operator: '*Celcom Axiata (LTE)',
          display: 'CELCOM / My Celcom / 502 19',
          availability: 'Yes'
      },
      {
          id: 2,
          operator: '*DiGi Telecom (LTE)',
          display: 'DiGi 1800 / DiGi /  MYMY18',
          availability: 'Yes'
      },
      {
          id: 3,
          operator: '*Maxis (LTE)',
          display: 'U Mobile / MYS 18 / MY 18',
          availability: 'Yes'
      },
      {
          id: 4,
          operator: 'U Mobile (LTE)',
          display: 'U Mobile / MYS 18 / MY 18',
          availability: 'Yes'
      }
  ];
  const handleTypeClick = (item: string) => {
      setType(item);
      setSelectedRowKeys([]);
 }
 console.log('type', type);
  return (
    <>
      <Head>
        <title>Table Component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <span className={styles.title}>Table Component</span>
        <div className={styles.tableFilter}>
            <span className={styles.typeText}>Type:</span>
            <div className={styles.tableType}>
                {selectedRowType.map((item, index) => <span
                    onClick={() => { handleTypeClick(item) }}
                    key ={index}
                    className={item === type ? styles.checked : styles.normal}>{item}</span>)}
           </div>
        </div>
        <Table
          columns={columns}
          data={data}
          showHead
          rowSelection={{
              type,
              selectedRowKeys,
              onSelect: (selectedRowKeys: number, selectedRows: []) => {
                  console.log('selectedRowKeys:', selectedRowKeys, selectedRows);
              }
          }}
        />
      </main>
    </>
  )
}
